### ISSUE TITLE
Crashed again~~

### ISSUE THREAD

**Issue by shibasofakingop** [Funwayguy/InfiniteInvo#23]
Alright, here is mine crash report, I can not run the game with this mod. Can somebody help me with this? I love this mod~~~~~~~~plz :D
Description: There was a severe problem during mod loading that has caused the game to fail

cpw.mods.fml.common.LoaderException: java.lang.NoSuchMethodError: net.minecraft.nbt.NBTTagCompound.setInteger(Ljava/lang/String;I)V
	at cpw.mods.fml.common.LoadController.transition(LoadController.java:162)
	at cpw.mods.fml.common.Loader.preinitializeMods(Loader.java:515)
	at cpw.mods.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:239)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:480)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:867)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:597)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: java.lang.NoSuchMethodError: net.minecraft.nbt.NBTTagCompound.setInteger(Ljava/lang/String;I)V
	at infiniteinvo.core.II_Settings.SaveToCache(II_Settings.java:29)
	at infiniteinvo.handlers.ConfigHandler.initConfigs(ConfigHandler.java:39)
	at infiniteinvo.core.InfiniteInvo.preInit(InfiniteInvo.java:49)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:597)
	at cpw.mods.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:513)
	at sun.reflect.GeneratedMethodAccessor2.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:597)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at cpw.mods.fml.common.LoadController.sendEventToModContainer(LoadController.java:208)
	at cpw.mods.fml.common.LoadController.propogateStateMessage(LoadController.java:187)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:597)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at cpw.mods.fml.common.LoadController.distributeStateMessage(LoadController.java:118)
	at cpw.mods.fml.common.Loader.preinitializeMods(Loader.java:513)
	... 10 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.7.10
	Operating System: Mac OS X (x86_64) version 10.10.2
	Java Version: 1.6.0_65, Apple Inc.
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Apple Inc.
	Memory: 159799088 bytes (152 MB) / 287477760 bytes (274 MB) up to 1060372480 bytes (1011 MB)
	JVM Flags: 5 total; -Xmx1G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M
	AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP v9.05 FML v7.10.85.1277 Minecraft Forge 10.13.2.1277 Optifine OptiFine_1.7.10_HD_B4 23 mods loaded, 23 mods active
	mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) Unloaded->Constructed->Pre-initialized
	FML{7.10.85.1277} [Forge Mod Loader] (forge-1.7.10-10.13.2.1277.jar) Unloaded->Constructed->Pre-initialized
	Forge{10.13.2.1277} [Minecraft Forge] (forge-1.7.10-10.13.2.1277.jar) Unloaded->Constructed->Pre-initialized
	BetterFonts{1.1.3} [BetterFonts] (minecraft.jar) Unloaded->Constructed->Pre-initialized
	battlegear2{1.0.7.0} [Mine & Blade Battlegear 2 - Bullseye] (1.7.10-MB_Battlegear2-Bullseye-1.0.7.0.jar) Unloaded->Constructed->Pre-initialized
	MoreWolvesMod{1.6.2} [MoreWolvesMod] ([1.7.10-1.7.2]MoreWolvesMod.jar) Unloaded->Constructed->Pre-initialized
	hearts{1.0} [Hearts] ([1.7.10][1.7.2] Heart Crystal 1.0.zip) Unloaded->Constructed->Pre-initialized
	bspkrsCore{6.15} [bspkrsCore] ([1.7.10]bspkrsCore-universal-6.15.jar) Unloaded->Constructed->Pre-initialized
	DamageIndicatorsMod{3.2.3} [Damage Indicators] ([1.7.10]DamageIndicatorsMod-3.2.3.jar) Unloaded->Constructed->Pre-initialized
	Treecapitator{1.7.10} [Treecapitator] ([1.7.10]Treecapitator-universal-2.0.4.jar) Unloaded->Constructed->Pre-initialized
	BuildMod{v1.0} [Build Mod] (CoroUtil-1.1.1.jar) Unloaded->Constructed->Pre-initialized
	CoroAI{v1.0} [CoroAI] (CoroUtil-1.1.1.jar) Unloaded->Constructed->Pre-initialized
	ExtendedRenderer{v1.0} [Extended Renderer] (CoroUtil-1.1.1.jar) Unloaded->Constructed->Pre-initialized
	ConfigMod{v1.0} [Extended Mod Config] (CoroUtil-1.1.1.jar) Unloaded->Constructed->Pre-initialized
	ElementalItems{4.0.0} [Elemental Items mod] (elementalitems-172-400-1079358127935812.jar) Unloaded->Constructed->Pre-initialized
	fairymod{0.5} [Fairy Mod] (fairymod-0.5-1.7.10.jar) Unloaded->Constructed->Pre-initialized
	InfernalMobs{1.5.9} [Infernal Mobs] (InfernalMobs1.5.9-1.7.10.jar) Unloaded->Constructed->Pre-initialized
	infiniteinvo{1.0.29} [InfiniteInvo] (InfiniteInvo-deobf-1.0.29.jar) Unloaded->Constructed->Errored
	IronChest{6.0.62.742} [Iron Chest] (ironchest-1.7.10-6.0.62.742-universal.jar) Unloaded->Constructed->Pre-initialized
	levelup{0.9} [Level Up!] (LevelUp!-0.9(1.7.10).jar) Unloaded->Constructed->Pre-initialized
	pvzmcw{Alpha 1.4.2} [Plants vs Zombies: Minecraft Warfare] (PvZ Minecraft Warfare Alpha 1.4.2.jar) Unloaded->Constructed->Pre-initialized
	UtilityMobs{3.1.1} [Utility Mobs] (UtilityMobs-1.7.10-3.1.1.jar) Unloaded->Constructed->Pre-initialized
	ZAMod{v1.9.5} [Zombie Awareness] (ZombieAwareness-1.9.6.jar) Unloaded->Constructed->Pre-initialized

**Comment by Funwayguy** [comment]
This is a very strange error because it seems that your Minecraft is crashing because it thinks the methods used for NBT tags don't exist. Not sure how or why that is occurring and sorry to say I have no idea where to even start on fixing that if even I can.

**Comment by shibasofakingop** [comment]
Yep brother,but no worries, it seems like i'm having a lot of troubles on mods, not just this one bro. Maybe i should redownload game or something, thx for helping, i don't know if anyone else got same problems with me XD~~~~~~~

**Comment by Badcholo** [comment]
Mine & Blade Battlegear 2 seems to not be compatible with a lot of mods. I finally just removed it.

**Comment by Alaberti** [comment]
Are you using the deof version of the mod?

**Comment by Funwayguy** [comment]
Seeing as this is an old issue and @Alaberti seems to have pointed out the cause I'm closing this. Downloading the correct version of the mod should fix this just fine.

**Comment by willabusta** [comment]
this error still persists today on version 1.0.44
Crashlog: 
---- Minecraft Crash Report ----
// Don't do that.

Time: 12/10/15 3:30 PM
Description: Unexpected error

java.lang.RuntimeException: Player inventory has been replaced with class infiniteinvo.inventory.BigInventoryPlayer
	at mods.battlegear2.BattlemodeHookContainerClass.onEntityJoin(BattlemodeHookContainerClass.java:62)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler_17_BattlemodeHookContainerClass_onEntityJoin_EntityJoinWorldEvent.invoke(.dynamic)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54)
	at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:138)
	at net.minecraft.world.World.func_72838_d(World.java:1334)
	at net.minecraft.client.multiplayer.WorldClient.func_72838_d(WorldClient.java:159)
	at net.minecraft.client.Minecraft.func_71353_a(Unknown Source)
	at net.minecraft.client.Minecraft.func_71403_a(Unknown Source)
	at net.minecraft.client.network.NetHandlerPlayClient.func_147282_a(Unknown Source)
	at net.minecraft.network.play.server.S01PacketJoinGame.func_148833_a(SourceFile:70)
	at net.minecraft.network.play.server.S01PacketJoinGame.func_148833_a(SourceFile:13)
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:212)
	at net.minecraft.client.Minecraft.func_71407_l(Unknown Source)
	at net.minecraft.client.Minecraft.func_71411_J(Unknown Source)
	at net.minecraft.client.Minecraft.func_99999_d(Unknown Source)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:310)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:394)
	at org.multimc.EntryPoint.listen(EntryPoint.java:170)
	at org.multimc.EntryPoint.main(EntryPoint.java:54)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at mods.battlegear2.BattlemodeHookContainerClass.onEntityJoin(BattlemodeHookContainerClass.java:62)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler_17_BattlemodeHookContainerClass_onEntityJoin_EntityJoinWorldEvent.invoke(.dynamic)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54)
	at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:138)
	at net.minecraft.world.World.func_72838_d(World.java:1334)
	at net.minecraft.client.multiplayer.WorldClient.func_72838_d(WorldClient.java:159)
	at net.minecraft.client.Minecraft.func_71353_a(Unknown Source)
	at net.minecraft.client.Minecraft.func_71403_a(Unknown Source)
	at net.minecraft.client.network.NetHandlerPlayClient.func_147282_a(Unknown Source)
	at net.minecraft.network.play.server.S01PacketJoinGame.func_148833_a(SourceFile:70)
	at net.minecraft.network.play.server.S01PacketJoinGame.func_148833_a(SourceFile:13)
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:212)

-- Affected level --
Details:
	Level name: MpServer
	All players: 1 total; [EntityClientPlayerMP['willabusta'/399, l='MpServer', x=8.50, y=66.62, z=8.50]]
	Chunk stats: MultiplayerChunkCache: 0, 0
	Level seed: 0
	Level generator: ID 02 - largeBiomes, ver 0. Features enabled: false
	Level generator options: 
	Level spawn location: World: (8,64,8), Chunk: (at 8,4,8 in 0,0; contains blocks 0,0,0 to 15,255,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 0 game time, 0 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: false
	Forced entities: 0 total; []
	Retry entities: 0 total; []
	Server brand: ~~NULL~~
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:373)
	at net.minecraft.client.Minecraft.func_71396_d(Unknown Source)
	at net.minecraft.client.Minecraft.func_99999_d(Unknown Source)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:310)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:394)
	at org.multimc.EntryPoint.listen(EntryPoint.java:170)
	at org.multimc.EntryPoint.main(EntryPoint.java:54)

-- System Details --
Details:
	Minecraft Version: 1.7.10
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_60, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 3267358640 bytes (3115 MB) / 5273812992 bytes (5029 MB) up to 5548015616 bytes (5291 MB)
	JVM Flags: 3 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xms3072m -Xmx5952m
	AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	IntCache: cache: 0, tcache: 0, allocated: 12, tallocated: 102
	FML: MCP v9.05 FML v7.10.99.99 Minecraft Forge 10.13.4.1470 168 mods loaded, 168 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJAAAA	mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJAAAA	FML{7.10.99.99} [Forge Mod Loader] (forge-1.7.10-10.13.4.1470-1.7.10-universal.jar) 
	UCHIJAAAA	Forge{10.13.4.1470} [Minecraft Forge] (forge-1.7.10-10.13.4.1470-1.7.10-universal.jar) 
	UCHIJAAAA	additionalresources{0.0.2} [Additional Resources] (additionalresources-1.7.10_0.0.3.jar) 
	UCHIJAAAA	CodeChickenCore{1.0.7.47} [CodeChicken Core] (minecraft.jar) 
	UCHIJAAAA	NotEnoughItems{1.0.5.118} [Not Enough Items] (NotEnoughItems-1.7.10-1.0.5.118-universal.jar) 
	UCHIJAAAA	OpenModsCore{0.7.2} [OpenModsCore] (minecraft.jar) 
	UCHIJAAAA	<CoFH ASM>{000} [CoFH ASM] (minecraft.jar) 
	UCHIJAAAA	battlegear2{1.7.10} [Mine & Blade Battlegear 2 - Bullseye] (1.7.10-MB_Battlegear2-Bullseye-1.0.8.0.jar) 
	UCHIJAAAA	Pistronics2{0.6.3} [Pistronics 2] (1.7.10-Pistronics2-v0.6.3.jar) 
	UCHIJAAAA	mod_LargeSign{2.0} [Large Sign] ([1.7.10-10.13.2.1230]Large Sign-2.0.jar) 
	UCHIJAAAA	ClothingCraft{1.2.1} [ClothingCraft] ([1.7.10] ClothingCraft 1.2.1.jar) 
	UCHIJAAAA	IC2{2.2.802-experimental} [IndustrialCraft 2] (industrialcraft-2-2.2.802-experimental.jar) 
	UCHIJAAAA	AdvancedSolarPanel{1.7.10-3.5.1} [Advanced Solar Panels] (AdvancedSolarPanel-1.7.10-3.5.1.jar) 
	UCHIJAAAA	AgriCraft{1.7.10-1.4.5} [AgriCraft] (AgriCraft-1.7.10-1.4.5.jar) 
	UCHIJAAAA	antiqueatlas{4.0.1a-1.7.2} [Antique Atlas] (antiqueatlas-4.0.1a-1.7.2.jar) 
	UCHIJAAAA	AquaTweaks{1.0} [AquaTweaks] (AquaTweaks-1.7.10-1.0.jar) 
	UCHIJAAAA	MovingWorld{1.7.10-1.8} [Moving World] (movingworld-1.7.10-1.8.jar) 
	UCHIJAAAA	ArchimedesShipsPlus{1.7.10-1.8} [Archimedes' Ships Plus] (archimedesshipsplus-1.7.10-1.8.jar) 
	UCHIJAAAA	Artifacts{1.1.3} [Artifacts] (Artifacts-1.1.3.jar) 
	UCHIJAAAA	audiodeath{${version}} [Audio Death] (audiodeath-1.7.10_0.4.0.jar) 
	UCHIJAAAA	autooredictconv{1.7.10-1.3.1} [Auto Ore Dictionary Converter] (autooredictconv-1.7.10-1.3.1.jar) 
	UCHIJAAAA	Backpack{2.0.1} [Backpack] (backpack-2.0.1-1.7.x.jar) 
	UCHIJAAAA	BetterSignsMod{1.6.4.B} [Better Signs Mod] (BetterSignsMod[v1.7.10.ported].jar) 
	UCHIJAAAA	malisiscore{1.7.10-0.12.4} [MalisisCore] (malisiscore-1.7.10-0.12.4.jar) 
	UCHIJAAAA	malisisdoors{1.7.10-1.9.1} [Malisis' Doors] (malisisdoors-1.7.10-1.9.1.jar) 
	UCHIJAAAA	BigDoors{1.7.10-1.0.0} [Big Doors] (BigDoors-1.7.10-1.0.0.jar) 
	UCHIJAAAA	CoFHCore{1.7.10R3.0.3B3} [CoFH Core] (CoFHCore-[1.7.10]3.0.3B3-301.jar) 
	UCHIJAAAA	MineFactoryReloaded{1.7.10R2.8.0} [MineFactory Reloaded] (MineFactoryReloaded-[1.7.10]2.8.0-104.jar) 
	UCHIJAAAA	ForgeMultipart{1.2.0.345} [Forge Multipart] (ForgeMultipart-1.7.10-1.2.0.345-universal.jar) 
	UCHIJAAAA	boilerplate{6.1.0} [Boilerplate] (boilerplate-1.7.10-6.1.0.jar) 
	UCHIJAAAA	cannibalism{1.1.1} [Cannibalism] (Cannibalism-1.1.1-1.7.10.jar) 
	UCHIJAAAA	CarpentersBlocks{3.3.7} [Carpenter's Blocks] (Carpenter's Blocks v3.3.7 - MC 1.7.10.jar) 
	UCHIJAAAA	chisel{2.9.3.9} [Chisel] (Chisel-2.9.3.9.jar) 
	UCHIJAAAA	Ztones{1.7.10} [Ztones] (Ztones-1.7.10-2.2.1.jar) 
	UCHIJAAAA	chiseltones{@VERSION@} [Chisel Tones] (ChiselTones-1.7.10-1.0-3.jar) 
	UCHIJAAAA	ChunkAnimator{@VERSION@} [Chunk Animator] (ChunkAnimator-MC1.7.10-1.0.1.jar) 
	UCHIJAAAA	rollercoaster{1.0} [rollercoaster] (Coastercraft_ver1.0.jar) 
	UCHIJAAAA	CompactWaterTurbines{1.1.0} [CompactWaterTurbines] (CompactWaterTurbines-1.7.10-1.1.1.jar) 
	UCHIJAAAA	ComputerCraft{1.73} [ComputerCraft] (ComputerCraft1.73.jar) 
	UCHIJAAAA	gud_cooler{1.1.5.0} [Coolers] (cooler-1.7.10-1.1.5.0.jar) 
	UCHIJAAAA	craftingslabs{1.7.10-1.1.0} [CraftingSlabs] (CraftingSlabs-1.7.10-1.1.0.jar) 
	UCHIJAAAA	Crowns{1.6} [Crowns] (crowns-1.7.10-1.6.jar) 
	UCHIJAAAA	dangersense{0.1.1} [DangerSense] (DangerSense-1.7.10-0.2.3.0.jar) 
	UCHIJAAAA	grim3212core{V0.2 - 1.7.10} [Grim3212 Core] (Grim3212 Core-V0.2 - 1.7.10.jar) 
	UCHIJAAAA	desertwells{V0.1 - 1.7.10} [Desert Wells] (Desert Wells-V0.1 - 1.7.10.jar) 
	UCHIJAAAA	divblocks{1.1} [DivBlocks] (DivBlocks-1.7.10-1.1.jar) 
	UCHIJAAAA	dlr{2.0.1} [Don's Lightning Rod] (Don's Lightning Rod-1.7.10-2.0.1.jar) 
	UCHIJAAAA	dragonfruit{V0.1 - 1.7.10} [Dragon Fruit] (Dragon Fruit-V0.1 - 1.7.10.jar) 
	UCHIJAAAA	EasyCrafting{1.7.10-2.0.1.16} [Easy Crafting] (EasyCrafting-1.7.10-2.0.1.16.jar) 
	UCHIJAAAA	eplus{3.0.2-d} [Enchanting Plus] (EnchantingPlus-1.7.10-3.0.2-d.jar) 
	UCHIJAAAA	extinguisher{V0.1 - 1.7.10} [Extinguisher] (Extinguisher-V0.1 - 1.7.10.jar) 
	UCHIJAAAA	ThermalFoundation{1.7.10R1.0.0} [Thermal Foundation] (ThermalFoundation-[1.7.10]1.0.0-81.jar) 
	UCHIJAAAA	ExtraUtilities{1.2.5} [Extra Utilities] (extrautilities-1.2.5.jar) 
	UCHIJAAAA	falsefire{1.0.1} [False Fire] (falsefire-1.0.1.jar) 
	UCHIJAAAA	fancypack{V0.1 - 1.7.10} [Fancy Pack] (Fancy Pack-V0.1 - 1.7.10.jar) 
	UCHIJAAAA	farseek{1.0.10} [Farseek] (Farseek-1.0.10.jar) 
	UCHIJAAAA	StealthwareCore{2.0} [StealthwareCore] (StealthwareCore-2.0.jar) 
	UCHIJAAAA	FearTweakPack{1.1} [Fearitude's Tweak Pack] (FearTweakPack-1.7.10-1.1.jar) 
	UCHIJAAAA	fireplaces{V0.1 - 1.7.10} [Fireplaces] (Fireplaces-V0.1 - 1.7.10.jar) 
	UCHIJAAAA	flatbedrock{V0.1 - 1.7.10} [Flat Bedrock] (Flat Bedrock-V0.1 - 1.7.10.jar) 
	UCHIJAAAA	fluxfyre{1.2.6} [FluxFyre] (FluxFyre-1.2.6.jar) 
	UCHIJAAAA	samsfragiletorches{1.7.10-1.0.0} [Fragile Torches] (FragileTorches-1.7.10-1.0.0.jar) 
	UCHIJAAAA	frames{V0.1 - 1.7.10} [Frames] (Frames-V0.1 - 1.7.10.jar) 
	UCHIJAAAA	fusrodah{V0.1 - 1.7.10} [FusRoDah] (FusRoDah-V0.1 - 1.7.10.jar) 
	UCHIJAAAA	ganyssurface{1.9.5} [Gany's Surface] (Ganys Surface-1.9.5.jar) 
	UCHIJAAAA	planetguyLib{1.9} [planetguyLib] (PlanetguyLib-1.9.1.jar) 
	UCHIJAAAA	planetguy_Gizmos{3.3} [Gizmos] (Gizmos-3.3.jar) 
	UCHIJAAAA	GollumCoreLib{2.0.0} [Gollum Core Lib] (Gollum_Core_Lib.1.7.10-2.0.0Beta1.0.jar) 
	UCHIJAAAA	gravityscience{V0.1 - 1.7.10} [Gravity Science] (Gravity Science-V0.1 - 1.7.10.jar) 
	UCHIJAAAA	Growthcraft{2.2.2} [Growthcraft] (growthcraft(community Edition)-2.2.2-complete.jar) 
	UCHIJAAAA	Growthcraft|Cellar{2.2.2} [Growthcraft Cellar] (growthcraft(community Edition)-2.2.2-complete.jar) 
	UCHIJAAAA	Growthcraft|Apples{2.2.2} [Growthcraft Apples] (growthcraft(community Edition)-2.2.2-complete.jar) 
	UCHIJAAAA	Growthcraft|Bamboo{2.2.2} [Growthcraft Bamboo] (growthcraft(community Edition)-2.2.2-complete.jar) 
	UCHIJAAAA	Growthcraft|Bees{2.2.2} [Growthcraft Bees] (growthcraft(community Edition)-2.2.2-complete.jar) 
	UCHIJAAAA	Growthcraft|Fishtrap{2.2.2} [Growthcraft Fishtrap] (growthcraft(community Edition)-2.2.2-complete.jar) 
	UCHIJAAAA	Growthcraft|Grapes{2.2.2} [Growthcraft Grapes] (growthcraft(community Edition)-2.2.2-complete.jar) 
	UCHIJAAAA	Growthcraft|Hops{2.2.2} [Growthcraft Hops] (growthcraft(community Edition)-2.2.2-complete.jar) 
	UCHIJAAAA	Growthcraft|Rice{2.2.2} [Growthcraft Rice] (growthcraft(community Edition)-2.2.2-complete.jar) 
	UCHIJAAAA	healthpack{V0.1 - 1.7.10} [Health Pack] (Health Pack-V0.1 - 1.7.10.jar) 
	UCHIJAAAA	HoloInventory{1.8.3.86} [HoloInventory] (HoloInventory-1.7.10-1.8.3.86.jar) 
	UCHIJAAAA	ImmersiveEngineering{0.5.4} [Immersive Engineering] (ImmersiveEngineering-0.5.4.jar) 
	UCHIJAAAA	immersiveintegration{0.5.4} [Immersive Integration] (immersiveintegration-0.5.4.jar) 
	UCHIJAAAA	infiniteinvo{1.0.44} [InfiniteInvo] (InfiniteInvo-1.0.44.jar) 
	UCHIJAAAA	integratedcircuits{1.7.10-0.9r35} [Integrated Circuits] (integratedcircuits-1.7.10-0.9r35.jar) 
	UCHIJAAAA	harvestcraft{1.7.10i} [Pam's HarvestCraft] (Pam's HarvestCraft 1.7.10i.jar) 
	UCHIJAAAA	jaffa{1.0} [JAFFA (HarvestCraft Addon)] (JAFFA-1.40.1.jar) 
	UCHIJAAAA	JoypadSplitscreenMod{1.7.2-0.1} [Joypad / SplitScreen Mod] (JoypadMod-1.7.10.jar) 
	UCHIJAAAA	Pads{2.3.3} [JumpPad++] (JumpPad++-1.7.10-2.3.3.jar) 
	UCHIJAAAA	lampposts{V0.1 - 1.7.10} [Lamp Posts] (Lamp Posts-V0.1 - 1.7.10.jar) 
	UCHIJAAAA	wuppy29_magicalexperience{1.1.5.0} [Magical Experience] (Magical Experience 1.7.10-1.1.5.1.jar) 
	UCHIJAAAA	Magneticraft{0.5.1} [Magneticraft] (magneticraft-0.5.1.jar) 
	UCHIJAAAA	MetallurgyCore{4.0.4} [Metallurgy Core] (MetallurgyCore-1.7.10-4.0.4.18.jar) 
	UCHIJAAAA	Metallurgy{4.0.6} [Metallurgy 4] (Metallurgy-1.7.10-4.0.6.80.jar) 
	UCHIJAAAA	metallurgychisel{1.0.0.11} [Metallurgy Chisel] (MetallurgyChisel-1.7.10-1.0.0.11.jar) 
	UCHIJAAAA	MineFactoryReloaded|CompatAppliedEnergistics{1.7.10R2.8.0} [MFR Compat: Applied Energistics] (MineFactoryReloaded-[1.7.10]2.8.0-104.jar) 
	UCHIJAAAA	MineFactoryReloaded|CompatAtum{1.7.10R2.8.0} [MFR Compat: Atum] (MineFactoryReloaded-[1.7.10]2.8.0-104.jar) 
	UCHIJAAAA	MineFactoryReloaded|CompatBackTools{1.7.10R2.8.0} [MFR Compat: BackTools] (MineFactoryReloaded-[1.7.10]2.8.0-104.jar) 
	UCHIJAAAA	MineFactoryReloaded|CompatBuildCraft{1.7.10R2.8.0} [MFR Compat: BuildCraft] (MineFactoryReloaded-[1.7.10]2.8.0-104.jar) 
	UCHIJAAAA	MineFactoryReloaded|CompatChococraft{1.7.10R2.8.0} [MFR Compat: Chococraft] (MineFactoryReloaded-[1.7.10]2.8.0-104.jar) 
	UCHIJAAAA	MineFactoryReloaded|CompatExtraBiomes{1.7.10R2.8.0} [MFR Compat: ExtraBiomes] (MineFactoryReloaded-[1.7.10]2.8.0-104.jar) 
	UCHIJAAAA	MineFactoryReloaded|CompatForestry{1.7.10R2.8.0} [MFR Compat: Forestry] (MineFactoryReloaded-[1.7.10]2.8.0-104.jar) 
	UCHIJAAAA	MineFactoryReloaded|CompatForgeMicroblock{1.7.10R2.8.0} [MFR Compat: ForgeMicroblock] (MineFactoryReloaded-[1.7.10]2.8.0-104.jar) 
	UCHIJAAAA	MineFactoryReloaded|CompatIC2{1.7.10R2.8.0} [MFR Compat: IC2] (MineFactoryReloaded-[1.7.10]2.8.0-104.jar) 
	UCHIJAAAA	MineFactoryReloaded|CompatMystcraft{1.7.10R2.8.0} [MFR Compat: Mystcraft] (MineFactoryReloaded-[1.7.10]2.8.0-104.jar) 
	UCHIJAAAA	MrTJPCoreMod{1.1.0.31} [MrTJPCore] (MrTJPCore-1.1.0.31-universal.jar) 
	UCHIJAAAA	ProjRed|Core{4.7.0pre9.92} [ProjectRed Core] (ProjectRed-1.7.10-4.7.0pre9.92-Base.jar) 
	UCHIJAAAA	ProjRed|Exploration{4.7.0pre9.92} [ProjectRed Exploration] (ProjectRed-1.7.10-4.7.0pre9.92-World.jar) 
	UCHIJAAAA	MineFactoryReloaded|CompatProjRed{1.7.10R2.8.0} [MFR Compat ProjectRed] (MineFactoryReloaded-[1.7.10]2.8.0-104.jar) 
	UCHIJAAAA	MineFactoryReloaded|CompatRailcraft{1.7.10R2.8.0} [MFR Compat: Railcraft] (MineFactoryReloaded-[1.7.10]2.8.0-104.jar) 
	UCHIJAAAA	MineFactoryReloaded|CompatSufficientBiomes{1.7.10R2.8.0} [MFR Compat: Sufficient Biomes] (MineFactoryReloaded-[1.7.10]2.8.0-104.jar) 
	UCHIJAAAA	MineFactoryReloaded|CompatThaumcraft{1.7.10R2.8.0} [MFR Compat: Thaumcraft] (MineFactoryReloaded-[1.7.10]2.8.0-104.jar) 
	UCHIJAAAA	ThermalExpansion{1.7.10R4.0.1} [Thermal Expansion] (ThermalExpansion-[1.7.10]4.0.1-182.jar) 
	UCHIJAAAA	MineFactoryReloaded|CompatThermalExpansion{1.7.10R2.8.0} [MFR Compat: Thermal Expansion] (MineFactoryReloaded-[1.7.10]2.8.0-104.jar) 
	UCHIJAAAA	MineFactoryReloaded|CompatTConstruct{1.7.10R2.8.0} [MFR Compat: Tinkers' Construct] (MineFactoryReloaded-[1.7.10]2.8.0-104.jar) 
	UCHIJAAAA	MineFactoryReloaded|CompatTwilightForest{1.7.10R2.8.0} [MFR Compat: TwilightForest] (MineFactoryReloaded-[1.7.10]2.8.0-104.jar) 
	UCHIJAAAA	MineFactoryReloaded|CompatVanilla{1.7.10R2.8.0} [MFR Compat: Vanilla] (MineFactoryReloaded-[1.7.10]2.8.0-104.jar) 
	UCHIJAAAA	MorePistons{2.0.0 Beta 1.0} [More Pistons] (More_Pistons-1.7.10-2.0.0Beta1.0.jar) 
	UCHIJAAAA	moreromannumerals{1.3} [More Roman Numerals] (moreromannumerals-1.3.jar) 
	UCHIJAAAA	multitools{V0.1 - 1.7.10} [Multi Tools] (Multi Tools-V0.1 - 1.7.10.jar) 
	UCHIJAAAA	OpenMods{0.7.2} [OpenMods] (OpenModsLib-1.7.10-0.7.2.jar) 
	UCHIJAAAA	OpenBlocks{1.4.2} [OpenBlocks] (OpenBlocks-1.7.10-1.4.2.jar) 
	UCHIJAAAA	clayspawn{1.7.10a} [Pam's Clay Spawn] (Pam's Clay Spawn 1.7.10a.jar) 
	UCHIJAAAA	desertcraft{1.7.2b} [Pam's DesertCraft] (Pam's DesertCraft 1.7.10a.zip) 
	UCHIJAAAA	getalltheseeds{1.7.10a} [Pam's Get all the Seeds!] (Pam's Get all the Seeds 1.7.10a.jar) 
	UCHIJAAAA	harvestthenether{1.7.10} [Pam's Harvest the Nether] (Pam's Harvest the Nether 1.7.10a.jar) 
	UCHIJAAAA	mobdropcrops{1.7.2a} [Pam's Mob Drop Crops] (Pam's Mob Drop Crops 1.7.10a.zip) 
	UCHIJAAAA	simplerecipes{1.7.10a} [Pam's Simple Recipes] (Pam's Simple Recipes 1.7.10a.jar) 
	UCHIJAAAA	placeableitems{1.4.4.1} [Placeable Items Mod] (placeableitems-1.4.4.1.jar) 
	UCHIJAAAA	pokeball{V0.1 - 1.7.10} [Pokeball] (Pokeball-V0.1 - 1.7.10.jar) 
	UCHIJAAAA	progressiveautomation{1.6.27} [Progressive Automation] (ProgressiveAutomation-1.7.10-1.6.27.jar) 
	UCHIJAAAA	ProjectE{1.7.10-PE1.9.4} [ProjectE] (ProjectE-1.7.10-PE1.9.4.jar) 
	UCHIJAAAA	ProjRed|Transmission{4.7.0pre9.92} [ProjectRed Transmission] (ProjectRed-1.7.10-4.7.0pre9.92-Integration.jar) 
	UCHIJAAAA	ProjRed|Transportation{4.7.0pre9.92} [ProjectRed Transportation] (ProjectRed-1.7.10-4.7.0pre9.92-Mechanical.jar) 
	UCHIJAAAA	ProjRed|Compatibility{4.7.0pre9.92} [ProjectRed Compatibility] (ProjectRed-1.7.10-4.7.0pre9.92-Compat.jar) 
	UCHIJAAAA	ProjRed|Integration{4.7.0pre9.92} [ProjectRed Integration] (ProjectRed-1.7.10-4.7.0pre9.92-Integration.jar) 
	UCHIJAAAA	ProjRed|Fabrication{4.7.0pre9.92} [ProjectRed Fabrication] (ProjectRed-1.7.10-4.7.0pre9.92-Fabrication.jar) 
	UCHIJAAAA	ProjRed|Illumination{4.7.0pre9.92} [ProjectRed Illumination] (ProjectRed-1.7.10-4.7.0pre9.92-Lighting.jar) 
	UCHIJAAAA	ProjRed|Expansion{4.7.0pre9.92} [ProjectRed Expansion] (ProjectRed-1.7.10-4.7.0pre9.92-Mechanical.jar) 
	UCHIJAAAA	rafradek_wallpaint{1.5.4} [Wall Painter] (rafradek_wallpaint-1.5.4.jar) 
	UCHIJAAAA	randomadditions{0.10} [RandomAdditions] (RandomAdditions Alpha 0.10 mc1.7.10.jar) 
	UCHIJAAAA	RandomThings{2.1.5} [Random Things] (RandomThings-2.1.5.jar) 
	UCHIJAAAA	JAKJ_RedstoneInMotion{2.8.5} [Remain In Motion] (RemainInMotion-2.8.5.jar) 
	UCHIJAAAA	repose{1.2.4} [Repose] (Repose-1.2.4.jar) 
	UCHIJAAAA	rftools{0.0} [RFTools] (rftools-1.01.jar) 
	UCHIJAAAA	SimpleLantern{1.0} [Simple Lantern] (SimpleLantern-1.7.10-1.0.jar) 
	UCHIJAAAA	slingshot{V0.1 - 1.7.10} [Slingshot] (Slingshot-V0.1 - 1.7.10.jar) 
	UCHIJAAAA	SolarExpansion{1.6a} [Solar Expansion] (SolarExpansion-Basic-1.6a.jar) 
	UCHIJAAAA	SolarFlux{1.7.10-0.8b} [Solar Flux] (SolarFlux-1.7.10-0.8b.jar) 
	UCHIJAAAA	soundfilters{0.8_for_1.7.X} [Sound Filters] (SoundFilters-0.8_for_1.7.X.jar) 
	UCHIJAAAA	splintermod{1.2} [Splinter Mod] (splintermod-1.2.jar) 
	UCHIJAAAA	staircraftmod{1.7} [Staircraft] (Staircraftmod 1.7 - 1.7.10 Forge.jar) 
	UCHIJAAAA	steamcraft2{B5.0.0} [Steamcraft 2] (steamcraft2-1.7.10-B5.0.0.jar) 
	UCHIJAAAA	superslopes{V0.1 - 1.7.10} [Super Slopes] (Super Slopes-V0.1 - 1.7.10.jar) 
	UCHIJAAAA	ThermalDynamics{1.7.10R1.0.0} [Thermal Dynamics] (ThermalDynamics-[1.7.10]1.0.0-122.jar) 
	UCHIJAAAA	ThrowableBricks{3.0} [Throwable Bricks Mod] (ThrowableBricks-3.0.jar) 
	UCHIJAAAA	inventorytweaks{1.58-645ca10-dirty} [Inventory Tweaks] (TweakedInventoryTweaks-1.58.jar) 
	UCHIJAAAA	wallpaper{V0.1 - 1.7.10} [Wallpaper] (Wallpaper-V0.1 - 1.7.10.jar) 
	UCHIJAAAA	workbenchupgrades{V0.1 - 1.7.10} [Workbench Upgrades] (Workbench Upgrades-V0.1 - 1.7.10.jar) 
	UCHIJAAAA	worldgenexpanded{V0.1 - 1.7.10} [WorldGenExpanded] (WorldGenExpanded-V0.1 - 1.7.10.jar) 
	UCHIJAAAA	WR-CBE|Core{1.4.1.9} [WR-CBE Core] (WR-CBE-1.7.10-1.4.1.9-universal.jar) 
	UCHIJAAAA	WR-CBE|Addons{1.4.1.9} [WR-CBE Addons] (WR-CBE-1.7.10-1.4.1.9-universal.jar) 
	UCHIJAAAA	WR-CBE|Logic{1.4.1.9} [WR-CBE Logic] (WR-CBE-1.7.10-1.4.1.9-universal.jar) 
	UCHIJAAAA	McMultipart{1.2.0.345} [Minecraft Multipart Plugin] (ForgeMultipart-1.7.10-1.2.0.345-universal.jar) 
	UCHIJAAAA	ForgeRelocation{0.0.1.4} [ForgeRelocation] (ForgeRelocation-1.7.10-0.0.1.4-universal.jar) 
	UCHIJAAAA	MCFrames{1.0} [MCFrames] (ForgeRelocation-1.7.10-0.0.1.4-universal.jar) 
	UCHIJAAAA	RelocationFMP{0.0.1.2} [RelocationFMP] (ForgeRelocationFMP-1.7.10-0.0.1.2-universal.jar) 
	UCHIJAAAA	ForgeMicroblock{1.2.0.345} [Forge Microblocks] (ForgeMultipart-1.7.10-1.2.0.345-universal.jar) 
	GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.5.0 NVIDIA 359.06' Renderer: 'GeForce GTX 950/PCIe/SSE2'
	OpenModsLib class transformers: [stencil_patches:FINISHED],[movement_callback:FINISHED],[map_gen_fix:FINISHED],[gl_capabilities_hook:FINISHED],[player_render_hook:FINISHED]
	CoFHCore: -[1.7.10]3.0.3B3-301
	MineFactoryReloaded: -[1.7.10]2.8.0-104
	ThermalFoundation: -[1.7.10]1.0.0-81
	ThermalExpansion: -[1.7.10]4.0.1-182
	ThermalDynamics: -[1.7.10]1.0.0-122
	Stencil buffer state: Function set: GL30, pool: forge, bits: 8
	Launched Version: MultiMC5
	LWJGL: 2.9.1
	OpenGL: GeForce GTX 950/PCIe/SSE2 GL version 4.5.0 NVIDIA 359.06, NVIDIA Corporation
	GL Caps: Using GL 1.3 multitexturing.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Anisotropic filtering is supported and maximum anisotropy is 16.
Shaders are available because OpenGL 2.1 is supported.

	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: [msi_conversion.zip]
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	Vec3 Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	Anisotropic Filtering: Off (1)
